# Generated by Django 5.0.13 on 2025-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
