# Generated by Django 5.0.13 on 2025-03-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
