# Generated by Django 5.0.13 on 2025-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
